# Generated by Django 5.2.8 on 2025-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_id',
            field=models.CharField(blank=True, help_text='Human-readable ID like AHMEDOV_A_11_N', max_length=50),
        ),
    ]
