# Generated by Django 5.2.8 on 2025-11-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, help_text='Student direction (natural/exact)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Student grade level (5-11)', null=True),
        ),
    ]
