# Generated by Django 5.2.8 on 2025-11-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_direction_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='target_grades',
            field=models.JSONField(blank=True, default=list, help_text='List of grades this test is for, empty for all grades'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(blank=True, help_text='Student registration date', null=True),
        ),
    ]
