# Generated by Django 5.2.8 on 2025-11-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_test_target_grades_user_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade_level',
        ),
        migrations.AddField(
            model_name='user',
            name='class_group',
            field=models.CharField(blank=True, help_text='Class group like 5-01', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='curator_class',
            field=models.CharField(blank=True, help_text='Curator class like 5-01', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_curator',
            field=models.BooleanField(default=False, help_text='Is this teacher a class curator?'),
        ),
    ]
