# Generated by Django 5.2.8 on 2025-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_grade_remove_user_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], default='medium', max_length=10),
        ),
    ]
