# Generated by Django 5.2.8 on 2025-11-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_testsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='testsession',
            new_name='api_testses_student_d40f10_idx',
            old_name='api_testsess_student__test_id_8b0b5f_idx',
        ),
        migrations.RenameIndex(
            model_name='testsession',
            new_name='api_testses_session_90762d_idx',
            old_name='api_testsess_session__b0dba1_idx',
        ),
    ]
