# Generated by Django 5.2.8 on 2025-11-22 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_api_testsess_student__test_id_8b0b5f_idx_api_testses_student_d40f10_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_date',
            field=models.DateTimeField(blank=True, help_text='When the user was banned', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason for banning'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Whether the user is banned'),
        ),
        migrations.AddField(
            model_name='user',
            name='unban_code',
            field=models.CharField(blank=True, help_text='4-digit code to unban the user', max_length=4),
        ),
        migrations.CreateModel(
            name='WarningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(help_text='Type of warning (tab_switch, f12, screenshot, etc.)', max_length=100)),
                ('warning_message', models.TextField(help_text='The warning message shown to the student')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='api.testsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
