# Generated by Django 5.2.8 on 2025-11-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_ban_date_user_ban_reason_user_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='is_banned_in_session',
            field=models.BooleanField(default=False, help_text='Whether student was banned during this session'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='unban_prompt_shown',
            field=models.BooleanField(default=False, help_text='Whether the unban prompt has been shown'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='warning_count',
            field=models.IntegerField(default=0, help_text='Number of warnings issued in this session'),
        ),
    ]
