# Generated by Django 5.2.8 on 2025-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_testsession_is_banned_in_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='target_grades',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of grades this test is for, empty for all grades', max_length=200),
        ),
    ]
