# Generated by Django 5.2.8 on 2025-11-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_test_target_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether the student has premium status'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_emoji_count',
            field=models.IntegerField(default=0, help_text='Number of premium emojis available'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_granted_date',
            field=models.DateTimeField(blank=True, help_text='When premium was granted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (can be GIF)', null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_status',
            field=models.CharField(blank=True, help_text='Custom status message', max_length=100),
        ),
    ]
