# Generated by Django 5.2.8 on 2025-12-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_is_premium_user_premium_emoji_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_gradient',
            field=models.JSONField(blank=True, default=dict, help_text='Background gradient settings for premium profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_emojis',
            field=models.JSONField(blank=True, default=list, help_text='List of selected premium emojis'),
        ),
    ]
