# Generated by Django 5.2.8 on 2025-12-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_background_gradient_user_selected_emojis'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
