# Generated by Django 5.2.8 on 2025-12-05 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('week', '1 Hafta'), ('month', '1 Oy'), ('year', '1 Yil')], max_length=10, unique=True)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price in USD', max_digits=6)),
                ('discounted_price', models.DecimalField(decimal_places=2, help_text='Discounted price in USD', max_digits=6)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plan_type'],
            },
        ),
    ]
