# Generated by Django 5.2.8 on 2025-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of premium subscription in USD', max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expiry_date',
            field=models.DateTimeField(blank=True, help_text='When premium expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_plan',
            field=models.CharField(blank=True, help_text='Premium plan type (week/month/year)', max_length=10),
        ),
    ]
