# Generated by Django 5.2.8 on 2025-12-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_premium_cost_user_premium_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_balance',
            field=models.IntegerField(default=0, help_text='Premium balance for performance-based premium (decreases with usage)'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_type',
            field=models.CharField(default='time_based', help_text='Type of premium: time_based or performance_based', max_length=20),
        ),
    ]
