# Generated by Django 5.2.8 on 2025-12-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_premium_balance_user_premium_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_earnings',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total earnings from premium sales commission', max_digits=10),
        ),
    ]
