# Generated by Django 5.2.8 on 2025-12-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_seller_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stars',
            field=models.IntegerField(default=0, help_text='Number of stars the student has'),
        ),
    ]
