# Generated by Django 5.2.8 on 2025-12-06 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(help_text='Number of stars in this package')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price in USD', max_digits=6)),
                ('discounted_price', models.DecimalField(decimal_places=2, help_text='Discounted price in USD', max_digits=6)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Discount percentage')),
                ('is_popular', models.BooleanField(default=False, help_text='Whether this package is marked as popular')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stars'],
            },
        ),
    ]
