# Generated by Django 5.2.8 on 2025-12-07 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_starpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the gift', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the gift')),
                ('image', models.ImageField(help_text='Gift image (should be 300x300px)', upload_to='gifts/')),
                ('star_cost', models.IntegerField(help_text='Number of stars required to purchase this gift')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this gift is available for purchase')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['star_cost'],
            },
        ),
        migrations.CreateModel(
            name='StudentGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_placed', models.BooleanField(default=False, help_text="Whether this gift is placed on the student's profile")),
                ('placement_position', models.IntegerField(blank=True, help_text='Position on profile (1-3)', null=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.gift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('student', 'placement_position')},
            },
        ),
    ]
