# Generated by Django 5.2.8 on 2025-12-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_gift_studentgift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='rarity',
            field=models.CharField(choices=[('common', 'Oddiy'), ('rare', 'Nodirkor'), ('epic', 'Epik'), ('legendary', 'Afsonaviy')], default='common', help_text='Rarity level of the gift', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='display_gift',
            field=models.ForeignKey(blank=True, help_text='Gift selected for display next to name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displayed_by', to='api.studentgift'),
        ),
    ]
