# Generated by Django 5.2.8 on 2025-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_hide_premium_from_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entered_ban_code',
            field=models.CharField(blank=True, help_text='Ban code entered by student in profile', max_length=4),
        ),
    ]
