# Generated by Django 5.2.8 on 2025-12-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_entered_ban_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ban_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ban_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unban_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entered_ban_code',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='warning_count',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='unban_prompt_shown',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='is_banned_in_session',
        ),
        migrations.DeleteModel(
            name='WarningLog',
        ),
    ]
