# Generated by Django 5.2.8 on 2025-12-15 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_ban_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_type', models.CharField(choices=[('class_rating', 'Sinflar reytingi'), ('custom', 'Maxsus')], default='class_rating', help_text='Type of event', max_length=20)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for the event', null=True, upload_to='event_banners/')),
                ('reward_stars', models.IntegerField(default=0, help_text='Number of stars to reward')),
                ('reward_description', models.CharField(blank=True, help_text='Description of the reward', max_length=200)),
                ('distribution_date', models.DateTimeField(help_text='When rewards should be automatically distributed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_class_groups', models.CharField(blank=True, help_text='Comma-separated list of class groups this event targets (empty for all)', max_length=500)),
                ('top_positions', models.IntegerField(default=3, help_text='Number of top positions to reward (1st, 2nd, 3rd, etc.)')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_awarded', models.IntegerField(default=0, help_text='Number of stars awarded')),
                ('position', models.IntegerField(blank=True, help_text='Position achieved (for rating events)', null=True)),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_claimed', models.BooleanField(default=False, help_text='Whether the student has seen/claimed this reward')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
