# Generated by Django 5.2.8 on 2025-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_event_eventreward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reward_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reward_stars',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_class_groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='top_positions',
        ),
        migrations.AddField(
            model_name='event',
            name='first_place_stars',
            field=models.IntegerField(default=10, help_text='Stars for 1st place'),
        ),
        migrations.AddField(
            model_name='event',
            name='second_place_stars',
            field=models.IntegerField(default=7, help_text='Stars for 2nd place'),
        ),
        migrations.AddField(
            model_name='event',
            name='third_place_stars',
            field=models.IntegerField(default=5, help_text='Stars for 3rd place'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('school_rating', 'Maktab reytingi'), ('custom', 'Maxsus')], default='school_rating', help_text='Type of event', max_length=20),
        ),
    ]
