# Generated by Django 5.2.8 on 2025-12-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_event_reward_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_class_groups',
            field=models.CharField(blank=True, help_text='Comma-separated list of class groups this event targets (empty for all)', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('school_rating', "O'quvchilar reytingi"), ('class_rating', 'Sinflar reytingi')], default='school_rating', help_text='Type of event', max_length=20),
        ),
    ]
