# Generated by Django 5.2.8 on 2025-12-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_event_target_class_groups_alter_event_event_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventReward',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
