# Generated by Django 5.2.8 on 2025-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_delete_event_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head_admin', 'Head Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('seller', 'Seller')], default='student', max_length=10),
        ),
    ]
