# Generated by Django 5.2.8 on 2025-12-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_premium_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of admin premium subscription in USD', max_digits=6),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_premium_expiry_date',
            field=models.DateTimeField(blank=True, help_text='When admin premium expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_premium_granted_date',
            field=models.DateTimeField(blank=True, help_text='When admin premium was granted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_premium_plan',
            field=models.CharField(blank=True, help_text='Admin premium plan type (week/month/year)', max_length=10),
        ),
    ]
