# Generated by Django 5.2.8 on 2025-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_user_admin_premium_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization or company the admin works for', max_length=100),
        ),
    ]
