# Generated by Django 5.2.8 on 2025-12-17 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who created this user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
