# Generated by Django 5.2.8 on 2025-12-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_user_created_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_premium_approved',
            field=models.BooleanField(default=False, help_text='Whether admin premium has been approved'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_premium_pending',
            field=models.BooleanField(default=False, help_text='Whether admin premium is pending approval'),
        ),
    ]
