# Generated by Django 5.2.8 on 2025-12-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_user_admin_premium_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_premium_from_others',
            field=models.BooleanField(default=False, help_text='Hide premium status from other users'),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_premium_from_self',
            field=models.BooleanField(default=False, help_text='Hide premium status from self'),
        ),
    ]
