# Generated by Django 5.2.8 on 2025-12-20 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_user_hide_premium_from_others_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('technical', 'Texnik yordam'), ('billing', "To'lov masalalari"), ('feature', 'Yangi funksiya taklifi'), ('partnership', 'Hamkorlik'), ('other', 'Boshqa')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('replied', 'Javob berilgan'), ('closed', 'Yopilgan')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reply', models.TextField(blank=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='api_contact_status_629118_idx'), models.Index(fields=['subject'], name='api_contact_subject_60d5f9_idx')],
            },
        ),
    ]
