# Generated by Django 5.2.8 on 2025-12-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_contactmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('student', 'test')},
        ),
    ]
