# Generated by Django 5.2.8 on 2026-01-17 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=10)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='updates_media/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
