# Generated by Django 5.2.8 on 2026-01-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_siteupdate_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteupdate',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='description_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='description_uz',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='title_en',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='title_ru',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='siteupdate',
            name='title_uz',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteupdate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteupdate',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
