# Generated by Django 5.2.8 on 2026-01-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_siteupdate_description_en_siteupdate_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_messages', models.BooleanField(default=True)),
                ('header_storage', models.BooleanField(default=True)),
                ('header_search', models.BooleanField(default=True)),
                ('header_language', models.BooleanField(default=True)),
                ('welcome_steps', models.JSONField(default=list)),
                ('feature_text_selection', models.BooleanField(default=True)),
                ('feature_home_save_button', models.BooleanField(default=True)),
                ('feature_flyer_animation', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
