# Generated by Django 5.2.8 on 2026-02-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head_admin', 'Head Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('seller', 'Seller'), ('content_manager', 'Content Manager')], default='student', max_length=20),
        ),
    ]
