# Generated by Django 5.2.8 on 2026-02-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_sitesettings_header_time_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_time',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_weather',
        ),
    ]
