# Generated by Django 5.2.8 on 2026-02-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_sitesettings_header_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(choices=[('Algebra', 'Algebra'), ('Astronomiya', 'Astronomiya'), ('Biologiya', 'Biologiya'), ('Chizmachilik', 'Chizmachilik'), ('Fizika', 'Fizika'), ('Geografiya', 'Geografiya'), ('Geometriya', 'Geometriya'), ('Huquq', 'Huquq'), ('IELTS', 'IELTS'), ('Informatika', 'Informatika'), ('Ingliz tili', 'Ingliz tili'), ('Iqtisodiyot', 'Iqtisodiyot'), ('Jismoniy tarbiya', 'Jismoniy tarbiya'), ('Kimyo', 'Kimyo'), ('Koreys tili', 'Koreys tili'), ('Matematika', 'Matematika'), ('Musiqa', 'Musiqa'), ('Ona tili va adabiyot', 'Ona tili va adabiyot'), ('Robototexnika', 'Robototexnika'), ('Rus tili', 'Rus tili'), ("San'at (Tasviriy san'at)", "San'at (Tasviriy san'at)"), ('Tarix', 'Tarix'), ('Tarbiya', 'Tarbiya'), ('Texnologiya', 'Texnologiya'), ('Boshqa', 'Boshqa')], default='Matematika', max_length=100),
        ),
    ]
