# Generated by Django 5.2.8 on 2026-02-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_test_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether this test is only for premium users'),
        ),
        migrations.AddField(
            model_name='test',
            name='star_price',
            field=models.IntegerField(default=0, help_text='Number of stars required to unlock this test'),
        ),
        migrations.AddField(
            model_name='user',
            name='owned_tests',
            field=models.JSONField(blank=True, default=list, help_text='List of test IDs owned by the student'),
        ),
    ]
