# Generated by Django 5.2.8 on 2026-02-09 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_test_is_premium_test_star_price_user_owned_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('stars', 'Stars Exchange'), ('money', 'Money Purchase')], default='stars', help_text='How premium was purchased', max_length=10)),
                ('plan_type', models.CharField(choices=[('week', '1 Hafta'), ('month', '1 Oy'), ('year', '1 Yil')], help_text='Premium plan type', max_length=10)),
                ('stars_used', models.IntegerField(default=0, help_text='Number of stars used for purchase')),
                ('money_spent', models.DecimalField(decimal_places=2, default=0, help_text='Money spent in USD', max_digits=6)),
                ('granted_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When premium was granted')),
                ('expiry_date', models.DateTimeField(help_text='When premium expires')),
                ('student', models.ForeignKey(help_text='Student who purchased premium', on_delete=django.db.models.deletion.CASCADE, related_name='premium_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Purchase',
                'verbose_name_plural': 'Premium Purchases',
                'ordering': ['-granted_date'],
            },
        ),
    ]
