# Generated by Django 5.2.8 on 2026-02-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_premium_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feature_anti_cheat',
            field=models.BooleanField(default=True),
        ),
    ]
