# Generated by Django 5.2.8 on 2026-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_sitesettings_feature_anti_cheat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_limit_reset_date',
            field=models.DateField(blank=True, help_text='Date when daily limit was last reset', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_tests_taken',
            field=models.IntegerField(default=0, help_text='Number of tests taken today'),
        ),
    ]
